/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { Lock__factory } from "./factories/Lock__factory";
